Selectable actions.
- Add a way to specify which build procudures to run.
- Sanitize existing build procedures.
- Remove uclibc build procedures as broken. Will add back later.

Signed-off-by: Alexey Zaytsev <alexey.zaytsev@gmail.com>

diff --git a/mktpkg b/mktpkg
--- a/mktpkg
+++ b/mktpkg
@@ -4,42 +4,35 @@
 # builder.
 #
 
+if [ -n "$DEBUG" ]; then
+    set -x
+fi
+
 TP_VERSION=0.3
+TPKG_MAINTAINER="Mikhail Gusarov <dottedmag@dottedmag.net>"
+
+ACT_LIST="do_binutils do_lld do_bs1_glibc do_bs1_gcc do_bs2_glibc do_gcc do_glibc do_ct_pkg"
 
 usage() {
+    echo -e "Usage: $0 <target-arch> [action] ..."
     echo
-    echo "Usage: $0 [--force] <target-arch>"
+    echo -e "\t<target-arch> must be a Debian architecture string."
     echo
-    echo "<target-arch> must be a Debian architecture string."
-    echo "<build-dir> must be a writable directory"
+    echo -e "\t[action] - one or more of: $ACTIONS"
+    for i in $ACT_LIST ; do
+        echo -e "\t\t$i"
+    done
+    echo
 }
 
-TEMP=$(getopt -o h --longoptions force: -n $0 -- "$@")
-if [ $? != 0 ]; then
-    exit 1
-fi
-eval set -- "$TEMP"
-
-while true; do
-    case "$1" in
-        --help) usage; exit;;
-        --force) FORCED_ACTION=1; shift;;
-        --) shift; break;;
-        *) exit 1;;
-    esac
-done
-
-TARGET="$1"
-if [ -z "$TARGET" ]; then
+if [ $# -lt 1 ] ; then
     usage
     exit 1
 fi
 
+TARGET=$1
 SRC_DIR=`pwd`
-
-if [ -z "$TPKG_MAINTAINER" ]; then
-    TPKG_MAINTAINER="Mikhail Gusarov <dottedmag@dottedmag.net>"
-fi
+LOG_BASE=log-$1
 
 #
 # Current gcc version (part of package name)
@@ -55,7 +48,7 @@ UCLIBC_DIR=$SRC_DIR/uclibc
 GLIBC_DIR=$SRC_DIR/glibc
 GCC_DIR=$SRC_DIR/gcc-$GCC_VERSION
 
-[ -n "$INSTALL_ROOTCMD" ] || INSTALL_ROOTCMD=sudo
+INSTALL_ROOTCMD=sudo
 
 MYARCH=$(dpkg --print-architecture)
 
@@ -73,6 +66,28 @@ if [ "x${HOST_GNU_TYPE}" = "x${BUILD_GNU_TYPE}" ] ; then
     exit 1
 fi
 
+# The build sequence is defined here.
+shift
+if [ $# -ne 0 ] ; then
+    ACTIONS=$@
+    # Explicit actions are performed no matter what
+    FORCED_ACTION="y"
+else
+    case "$HOST_GNU_SYSTEM" in
+        *uclibc*)
+            echo "uclibc is not supported yet."
+            ;;
+        *gnu*)
+            ACTIONS="do_binutils do_lld do_bs1_glibc do_bs1_gcc do_bs2_glibc do_gcc do_glibc do_ct_pkg"
+            ;;
+        *)
+            echo "Unknown libc requested: $HOST_GNU_SYSTEM"
+            ;;
+    esac
+fi
+
+
+
 # get source package's version from its debian/changelog
 # $1 -- path to unpacked sources
 _get_version() {
@@ -88,27 +103,25 @@ BINUTILS_DEBPKG="${BINUTILS_PKGNAME}_${BINUTILS_V}_${BUILD_ARCH}.deb"
 
 LLD_V=$(_get_version "$LLD_DIR")
 LLD_CROSSPKGNAME="linux-libc-dev-${HOST_ARCH}-cross"
+LLD_DEBCROSS="{$LLD_CROSSPKGNAME}_${LLD_V}_all.deb"
 LLD_DEBPKG="linux-libc-dev_${LLD_V}_${HOST_ARCH}.deb"
 
-case "$LHOST_GNU_SYSTEM" in
-    *uclibc*)
-        UCLIBC_V=$(_get_version "$UCLIBC_DIR")
-        ;;
-    *)
-        GLIBC_V=$(_get_version "$GLIBC_DIR")
+UCLIBC_V=$(_get_version "$UCLIBC_DIR")
+GLIBC_V=$(_get_version "$GLIBC_DIR")
 
-        # Stage 1
-        GLIBC_DEV_HEADERS_CROSSPKGNAME="libc6-dev-headers-${HOST_ARCH}-cross"
-        GLIBC_DEV_HEADERS_DEBPKG="libc6-dev-headers_${GLIBC_V}_${HOST_ARCH}.deb"
+# Stage 1
+GLIBC_DEV_HEADERS_CROSSPKGNAME="libc6-dev-headers-${HOST_ARCH}-cross"
+GLIBC_DEV_HEADERS_DEBCROSS="${GLIBC_DEV_HEADERS_CROSSPKGNAME}_${GLIBC_V}_all.deb"
+GLIBC_DEV_HEADERS_DEBPKG="libc6-dev-headers_${GLIBC_V}_${HOST_ARCH}.deb"
 
-        # Stage 2&3
-        GLIBC_CROSSPKGNAME="libc6-${HOST_ARCH}-cross"
-        GLIBC_DEBPKG="libc6_${GLIBC_V}_${HOST_ARCH}.deb"
+# Stage 2&3
+GLIBC_CROSSPKGNAME="libc6-${HOST_ARCH}-cross"
+GLIBC_DEBCROSS="${GLIBC_CROSSPKGNAME}_${GLIBC_V}_all.deb"
+GLIBC_DEBPKG="libc6_${GLIBC_V}_${HOST_ARCH}.deb"
 
-        GLIBC_DEV_CROSSPKGNAME="libc6-dev-${HOST_ARCH}-cross"
-        GLIBC_DEV_DEBPKG="libc6-dev_${GLIBC_V}_${HOST_ARCH}.deb"
-        ;;
-esac
+GLIBC_DEV_CROSSPKGNAME="libc6-dev-${HOST_ARCH}-cross"
+GLIBC_DEV_DEBCROSS="${GLIBC_DEV_CROSSPKGNAME}_${GLIBC_V}_all.deb"
+GLIBC_DEV_DEBPKG="libc6-dev_${GLIBC_V}_${HOST_ARCH}.deb"
 
 GCC_V=$(_get_version "$GCC_DIR")
 case "$GCC_VERSION" in
@@ -132,36 +145,24 @@ GXX_PKGNAME="g++-${GCC_VERSION}-${DEBPKG_HOST_GNU_TYPE}"
 GXX_DEBPKG="${GXX_PKGNAME}_${GCC_V}_${BUILD_ARCH}.deb"
 
 LIBGCC_CROSSPKGNAME="libgcc1-${HOST_ARCH}-cross"
+LIBGCC_DEBCROSS="${LIBGCC_CROSSPKGNAME}_${GCC_V}_all.deb"
 LIBGCC_DEBPKG="libgcc1_${GCC_V}_${HOST_ARCH}.deb"
 
 LIBSTDCXX_CROSSNAME="libstdc++${GXX_SONAME}-${HOST_ARCH}-cross"
+LIBSTDCXX_DEBCROSS="${LIBSTDCXX_CROSSNAME}_${GCC_V}_all.deb"
 LIBSTDCXX_DEBPKG="libstdc++${GXX_SONAME}_${GCC_V}_${HOST_ARCH}.deb"
 
 LIBSTDCXX_DEV_CROSSNAME="libstdc++${GXX_SONAME}-${GCC_VERSION}-dev-${HOST_ARCH}-cross"
+LIBSTDCXX_DEV_DEBCROSS="${LIBSTDCXX_DEV_CROSSNAME}_${GCC_V}_all.deb"
 LIBSTDCXX_DEV_DEBPKG="libstdc++${GXX_SONAME}-${GCC_VERSION}-dev_${GCC_V}_${HOST_ARCH}.deb"
 
 # banner
 echo "Building cross toolchain packages"
 echo "---------------------------------"
 echo "Host architecture: $MYARCH"
-echo "Target cpu: $LHOST_GNU_CPU"
-echo "Target os: $LHOST_GNU_SYSTEM"
-
-# check for error condition, scream and die if needed
-# This one should be called right after the command that
-# can potentially trigger the error condition.
-# $1 -- string describing the action (e.g., "installing")
-# $2 -- name of the package, on which this action was performed
-_checkerr() {
-    local _err="$?"
-    local _what="$1"
-    local _pkg="$2"
-
-    if [ $_err -ne 0 ]; then
-        echo "Something wicked happened when $_what $_pkg, exiting."
-        exit 1
-    fi
-}
+echo "Target cpu: $HOST_GNU_CPU"
+echo "Target os: $HOST_GNU_SYSTEM"
+echo "Actions: $ACTIONS"
 
 # call dpkg-cross to convert a target package into a -cross package
 # and perform cross-installation
@@ -173,20 +174,16 @@ _crossinst() {
 }
 
 # check if a package is installed
-# $@ -- binary package names
+# $@ -- binary package name
 _checkinst() {
-    local _pkg
-    local _status
+    if [ -n $FORCED_ACTION ]; then
+        exit
+    fi
 
-    while [ -n "$1" ]; do
-        _pkg="$1"
-        _status=`dpkg -s "$_pkg" 2>/dev/null | grep '^Status: ' | cut -d' ' -f4`
-        if [ "$?" != "0" -o "$_status" != "installed" ]; then
-            exit
-        fi
-
-        shift
-    done
+    _status=`dpkg -s "$1" 2>/dev/null | grep '^Status: ' | cut -d' ' -f4`
+    if [ "$?" != "0" -o "$_status" != "installed" ]; then
+        exit
+    fi
 
     echo "installed"
 }
@@ -201,278 +198,113 @@ _checkinst() {
 # binutils #
 ############
 do_binutils() {
-    echo "do_binutils"
-
-    if [ -z "`_checkinst $BINUTILS_PKGNAME`" -o -n "$FORCED_ACTION" ]; then
-        build_binutils
-        install_binutils
+    if [ -z "`_checkinst $BINUTILS_PKGNAME`" ]; then
+        rm -f $BINUTILS_DEBPKG
+        ( cd $BINUTILS_DIR ; env TARGET=$HOST_ARCH dpkg-buildpackage -us -uc -b )
+        $INSTALL_ROOTCMD dpkg -i $BINUTILS_DEBPKG
     else
         echo "binutils ($BINUTILS_PKGNAME) appears to be installed, skipping"
     fi
 }
 
-build_binutils() {
-    pushd "$BINUTILS_DIR"
-    ARCH=$LHOST_ARCH
-    ( env TARGET=$ARCH dpkg-buildpackage -us -uc -b )
-    _checkerr building binutils
-    popd
-}
-
-install_binutils() {
-    $INSTALL_ROOTCMD dpkg -i "$SRC_DIR/$BINUTILS_DEBPKG"
-    _checkerr installing binutils
-}
-
-########################
+##################
 # linux-libc-dev #
-########################
+##################
 do_lld() {
-    echo "do_lld"
+    if [ -z "`_checkinst $LLD_CROSSPKGNAME`" ]; then
 
-    if [ -z "`_checkinst $LLD_CROSSPKGNAME`" -o -n "$FORCED_ACTION" ]; then
-        build_lld
-        install_lld
+    rm -f $LLD_DEBPKG $LLD_DEBCROSS
+    ( cd $LLD_DIR ; dpkg-buildpackage -uc -us -a${HOST_ARCH} -b )
+    _crossinst $LLD_DEBPKG
+
     else
         echo "linux-libc-dev ($LLD_CROSSPKGNAME) appears to be installed, skipping"
     fi
 }
 
-build_lld() {
-    pushd "$LLD_DIR"
-    dpkg-buildpackage -uc -us -a${HOST_ARCH} -b
-    _checkerr building linux-libc-dev
-    popd
-}
-
-install_lld() {
-    _crossinst $LLD_DEBPKG
-    _checkerr installing linux-libc-dev
-}
-
-# --- libraries ---
-
-do_stage1_libc() {
-    echo "do_stage1_libc"
-
-    case "$LHOST_GNU_SYSTEM" in
-        *uclibc*) do_uclibc_bs;;
-        *gnu*) do_glibc_bs;;
-        *) echo "Unknown OS"; exit 1;;
-    esac
-}
-
-do_stage2_libc() {
-    echo "do_stage2_libc"
-
-    case "$LHOST_GNU_SYSTEM" in
-        *uclibc*) do_uclibc;;
-        *gnu*) do_glibc_bs2;;
-        *) echo "Unknown OS"; exit 1;;
-    esac
-}
-
-##########
-# uclibc #
-##########
-do_uclibc_bs() {
-    PKGNAME1="libuclibc-bootstrap-${HOST_ARCH}-cross"
-
-    if [ -z "`_checkinst $PKGNAME1`" -o -n "$FORCED_ACTION" ]; then
-        if [ -z "`_checkinst $PKGNAME1`" -o -n "$FORCED_ACTION" ]; then
-            build_uclibc_bs
-            install_uclibc_bs
-        else
-            echo "uclibc ($PKGNAME1) appears to be installed, skipping"
-        fi
-    else
-        echo "uclibc ($PKGNAME1) appears to be installed, skipping"
-    fi
-}
-
-build_uclibc_bs() {
-    pushd "$UCLIBC_DIR"
-    ( env DEB_CROSS_BOOTSTRAP=yes \
-        dpkg-buildpackage -uc -us -a${HOST_ARCH} \
-        -b )
-    _checkerr building "bootstrap uclibc"
-    popd
-}
-
-install_uclibc_bs() {
-    PKGNAME="libuclibc-bootstrap_${UCLIBC_V}_${HOST_ARCH}.deb"
-    _crossinst $PKGNAME
-    _checkerr installing "bootstrap uclibc"
-}
-
-do_uclibc() {
-    PKGNAME="libuclibc0-${HOST_ARCH}-cross libuclibc-dev-${HOST_ARCH}-cross"
-
-    if [ -z "`_checkinst $PKGNAME`" -o -n "$FORCED_ACTION" ]; then
-        build_uclibc
-        install_uclibc
-    else
-        echo "uclibc ($PKGNAME) appears to be installed, skipping"
-    fi
-}
-
-build_uclibc() {
-    $INSTALL_ROOTCMD dpkg -P libuclibc-bootstrap-${HOST_ARCH}-cross
-    pushd "$UCLIBC_DIR"
-    ( dpkg-buildpackage -uc -us -a${HOST_ARCH} -b )
-    _checkerr building uclibc
-    popd
-}
-
-install_uclibc() {
-    PKGPREFIX="${UCLIBC_V}_${HOST_ARCH}.deb"
-    PKGNAMES="libuclibc-dev_${PKGPREFIX} ldso-uclibc_${PKGPREFIX} libc-uclibc_${PKGPREFIX} libm-uclibc_${PKGPREFIX} libpthread-uclibc_${PKGPREFIX} libdl-uclibc_${PKGPREFIX} librt-uclibc_${PKGPREFIX} libresolv-uclibc_${PKGPREFIX} libcrypt-uclibc_${PKGPREFIX} libutil-uclibc_${PKGPREFIX} libnsl-uclibc_${PKGPREFIX}"
-    echo "Installing Uclibc packages: $PKGNAMES"
-    _crossinst $PKGNAMES
-    _checkerr installing uclibc
-}
-
 #########
 # glibc #
 #########
-do_glibc_bs() {
-    PKGNAME1="$GLIBC_DEV_HEADERS_CROSSPKGNAME"
-    PKGNAME2="$GLIBC_CROSSPKGNAME $GLIBC_DEV_CROSSPKGNAME"
+do_bs1_glibc() {
+    if [ -z "`_checkinst $GLIBC_DEV_CROSSPKGNAME`" ]; then
+        if [ -z "`_checkinst $GLIBC_DEV_HEADERS_CROSSPKGNAME`"]; then
 
-    if [ -z "`_checkinst $PKGNAME2`" -o -n "$FORCED_ACTION" ]; then
-        if [ -z "`_checkinst $PKGNAME1`" -o -n "$FORCED_ACTION" ]; then
-            build_glibc_bs
-            install_glibc_bs
+            rm -f $GLIBC_DEV_HEADERS_DEBPKG $GLIBC_DEV_HEADERS_DEBCROSS
+            ( cd $GLIBC_DIR ; env DEB_CROSS_BOOTSTRAP=yes \
+                dpkg-buildpackage -uc -us -a${HOST_ARCH} -b )
+
+            _crossinst $GLIBC_DEV_HEADERS_DEBPKG
+
         else
-            echo "glibc ($PKGNAME1) appears to be installed, skipping"
+            echo "glibc ($GLIBC_DEV_CROSSPKGNAME) appears to be installed, skipping"
         fi
     else
-        echo "glibc ($PKGNAME2) appears to be installed, skipping"
+        echo "glibc ($GLIBC_DEV_HEADERS_CROSSPKGNAME) appears to be installed, skipping"
     fi
 }
 
-build_glibc_bs() {
-    pushd "$GLIBC_DIR"
-    ( env DEB_CROSS_BOOTSTRAP=yes \
-        dpkg-buildpackage -uc -us -a${HOST_ARCH} -b )
-    _checkerr building "bootstrap glibc"
-    popd
-}
 
-install_glibc_bs() {
-    _crossinst $GLIBC_DEV_HEADERS_DEBPKG
-    _checkerr installing "bootstrap glibc"
-}
+do_bs2_glibc() {
+    if [ -z "`_checkinst $GLIBC_DEV_CROSSPKGNAME`" ]; then
 
-do_glibc_bs2() {
-    PKGNAME="$GLIBC_CROSSPKGNAME $GLIBC_DEV_CROSSPKGNAME"
+        rm -f $GLIBC_DEBPKG $GLIBC_DEV_DEBPKG $GLIBC_DEBCROSS $GLIBC_DEV_DEBCROSS
+        ( cd $GLIBC_DIR ; env DEB_CROSS_BOOTSTRAP=second \
+            dpkg-buildpackage -uc -us -a${HOST_ARCH} -b )
 
-    if [ -z "`_checkinst $PKGNAME`" -o -n "$FORCED_ACTION" ]; then
-        build_glibc_bs2
-        install_glibc_bs2
+         $INSTALL_ROOTCMD dpkg -P $GLIBC_DEV_HEADERS_CROSSPKGNAME
+        _crossinst $GLIBC_DEBPKG $GLIBC_DEV_DEBPKG
+
     else
-        echo "glibc ($PKGNAME) appears to be installed, skipping"
+        echo "glibc ($GLIBC_DEV_CROSSPKGNAME) appears to be installed, skipping"
     fi
-}
-
-build_glibc_bs2() {
-    pushd "$GLIBC_DIR"
-    ( env DEB_CROSS_BOOTSTRAP=second \
-        dpkg-buildpackage -uc -us -a${HOST_ARCH} -b )
-    _checkerr building glibc
-    popd
-}
-
-install_glibc_bs2() {
-    $INSTALL_ROOTCMD dpkg -P $GLIBC_DEV_HEADERS_CROSSPKGNAME
-    _crossinst $GLIBC_DEBPKG $GLIBC_DEV_DEBPKG
-    _checkerr installing glibc
 }
 
 do_glibc() {
-    build_glibc
-    install_glibc
-}
+    # We perform this step unconditionally because the final and bs2 package names are the same
+    rm -f $GLIBC_DEBPKG $GLIBC_DEV_DEBPKG $GLIBC_DEBCROSS $GLIBC_DEV_DEBCROSS
 
-build_glibc() {
-    pushd "$GLIBC_DIR"
-    ( dpkg-buildpackage -uc -us -a${HOST_ARCH} -b )
-    _checkerr building glibc
-    popd
-}
-
-install_glibc() {
+    ( cd $GLIBC_DIR ; dpkg-buildpackage -uc -us -a${HOST_ARCH} -b )
     _crossinst $GLIBC_DEBPKG $GLIBC_DEV_DEBPKG
-    _checkerr installing glibc
 }
 
 #######
 # gcc #
 #######
-do_stage1() {
-    echo "do_stage1"
+do_bs1_gcc() {
+    if [ -z "`_checkinst $GCC_PKGNAME`" ]; then
 
-    PKGNAMES="$GCC_PKGNAME $GCC_BASE_PKGNAME $CPP_PKGNAME $LIBGCC_CROSSPKGNAME"
+        rm -f $GCC_DEBPKG $GCC_BASE_DEBPKG $CPP_DEBPKG $LIBGCC_DEBCROSS
+        ( cd $GCC_DIR ; env GCC_TARGET=${HOST_ARCH} DEB_CROSS=yes DEB_CROSS_BOOTSTRAP=yes \
+            dpkg-buildpackage -uc -us -b )
 
-    if [ -z "`_checkinst $PKGNAMES`" -o -n "$FORCED_ACTION" ]; then
-        do_stage1_libc
-        build_gcc_bs
-        install_gcc_bs
+        _crossinst $LIBGCC_DEBPKG
+        $INSTALL_ROOTCMD dpkg -i --force-depends $GCC_BASE_DEBPKG $GCC_DEBPKG $CPP_DEBPKG
+
     else
-        echo "base compiler ($PKGNAMES) appears to be installed, skipping"
+        echo "base compiler ($GCC_PKGNAME) appears to be installed, skipping"
     fi
 }
 
-build_gcc_bs() {
-    pushd "$GCC_DIR"
-    ARCH=${HOST_ARCH}
-    ( env GCC_TARGET=${ARCH} DEB_CROSS=yes DEB_CROSS_BOOTSTRAP=yes \
-        dpkg-buildpackage -uc -us -b -d)
-    _checkerr building "bootstrap gcc"
-    popd
-}
+do_gcc() {
+    if [ -z "`_checkinst $LIBSTDCXX_DEV_CROSSNAME`" ]; then
 
-install_gcc_bs() {
-    _crossinst $LIBGCC_DEBPKG
-    _checkerr installing "bootstrap gcc"
+        rm -f $GCC_DEBPKG $CPP_DEBPKG $GXX_DEBPKG $LIBGCC_DEBPKG $LIBGCC_DEBCROSS $LIBSTDCXX_DEBPKG $LIBSTDCXX_DEV_DEBPKG $LIBSTDCXX_DEBCROSS $LIBSTDCXX_DEV_DEBCROSS
+        $INSTALL_ROOTCMD dpkg -P $GCC_PKGNAME $GCC_BASE_PKGNAME $CPP_PKGNAME \
+             $GXX_PKGNAME $LIBGCC_CROSSPKGNAME $LIBSTDCXX_CROSSNAME $LIBSTDCXX_DEV_CROSSNAME
 
-    PKGNAMES="$GCC_BASE_DEBPKG $GCC_DEBPKG $CPP_DEBPKG"
-    ( cd "$SRC_DIR"; $INSTALL_ROOTCMD dpkg -i --force-depends $PKGNAMES )
-    _checkerr installing "bootstrap gcc"
-}
+        ( cd $GCC_DIR ; env GCC_TARGET=${ARCH} DEB_CROSS=yes DEB_TARGET_LIBCXX=yes \
+            dpkg-buildpackage -uc -us -d )
 
-do_stage2() {
-    PKGNAMES="$GCC_PKGNAME $GCC_BASE_PKGNAME $CPP_PKGNAME $GXX_PKGNAME $LIBGCC_CROSSPKGNAME $LIBSTDCXX_CROSSNAME $LIBSTDCXX_DEV_CROSSNAME"
+        _crossinst $LIBGCC_DEBPKG $LIBSTDCXX_DEBPKG $LIBSTDCXX_DEV_DEBPKG
+        $INSTALL_ROOTCMD dpkg -i $GCC_BASE_DEBPKG $GCC_DEBPKG $CPP_DEBPKG $GXX_DEBPKG
 
-    if [ -z "`_checkinst $PKGNAMES`" -o -n "$FORCED_ACTION" ]; then
-        do_stage2_libc
-        build_gcc
-        install_gcc
     else
-        echo "compiler ($PKGNAMES) appears to be installed, skipping"
+        echo "compiler ($LIBSTDCXX_DEV_CROSSNAME) appears to be installed, skipping"
     fi
-}
-
-build_gcc() {
-    PKGLIST_GCC="$GCC_PKGNAME $GCC_BASE_PKGNAME $CPP_PKGNAME $GXX_PKGNAME $LIBGCC_CROSSPKGNAME $LIBSTDCXX_CROSSNAME $LIBSTDCXX_DEV_CROSSNAME"
-    $INSTALL_ROOTCMD dpkg -P ${PKGLIST_GCC}
-    pushd "$GCC_DIR"
-    ARCH=${HOST_ARCH}
-    ( env GCC_TARGET=${ARCH} DEB_CROSS=yes DEB_TARGET_LIBCXX=yes \
-        dpkg-buildpackage -uc -us -d )
-    _checkerr building gcc
-    popd
-}
-
-install_gcc() {
-    _crossinst $LIBGCC_DEBPKG $LIBSTDCXX_DEBPKG $LIBSTDCXX_DEV_DEBPKG
-    ( cd "$SRC_DIR"; $INSTALL_ROOTCMD dpkg -i $GCC_BASE_DEBPKG $GCC_DEBPKG $CPP_DEBPKG $GXX_DEBPKG)
-    _checkerr installing gcc
 }
 
 # -- toolchain metapackage --
-
-install_cross_toolchain_pkg() {
+do_ct_pkg() {
     # render package's "Depends:" header
     BINUTILS_PKGDEP="$BINUTILS_PKGNAME (= ${BINUTILS_V})"
 
@@ -483,18 +315,19 @@ install_cross_toolchain_pkg() {
     PROVIDES="build-essential-${BUILD_ARCH}-cross, cross-toolchain-${HOST_ARCH}-cross, cross-toolchain-${HOST_ARCH}-dcv1"
     CONFLICTS=""
 
-    DEPENDS="$BINUTILS_PKGDEP, $LLD_PKGDEP, $GCC_PKGDEP,"
 
     case "$HOST_ARCH_OS" in
         uclibc)
-            UCLIBC_PKGDEP="libuclibc0-${HOST_ARCH}-cross (= ${UCLIBC_V}), libuclibc-dev-${HOST_ARCH}-cross (= ${UCLIBC_V})"
-            DEPENDS="$DEPENDS $UCLIBC_PKGDEP";;
+            LIBC_PKGDEP="libuclibc0-${HOST_ARCH}-cross (= ${UCLIBC_V}), libuclibc-dev-${HOST_ARCH}-cross (= ${UCLIBC_V})"
+            ;;
         linux)
-            GLIBC_PKGDEP="$GLIBC_CROSSPKGNAME (= ${GLIBC_V}), $GLIBC_DEV_CROSSPKGNAME (= ${GLIBC_V})"
-            DEPENDS="$DEPENDS $GLIBC_PKGDEP";;
+            LIBC_PKGDEP="$GLIBC_CROSSPKGNAME (= ${GLIBC_V}), $GLIBC_DEV_CROSSPKGNAME (= ${GLIBC_V})"
+            ;;
         *)
             echo "Unknown OS"; exit 1;;
     esac
+
+    DEPENDS="$BINUTILS_PKGDEP, $LLD_PKGDEP, $GCC_PKGDEP, $LIBC_PKGDEP"
 
     TPKG_PKGNAME="${HOST_ARCH}-cross-toolchain"
     TPKG_PKGDIR=$SRC_DIR/$TPKG_PKGNAME
@@ -547,19 +380,15 @@ EOF
     dpkg-name -o $SRC_DIR/${TPKG_PKGNAME}.deb
 }
 
-do_binutils
-do_lld
-do_stage1
-do_stage2
+run_action () {
+    echo "Running '$1'..."
+    ( $1 ) 2>&1 | tee $LOG_BASE-$1.log
+    if [ $? -ne 0 ] ; then
+        echo "Action '$1' failed, see logs in '$LOG_BASE-$1.log'"
+    fi
+}
 
-case "$HOST_GNU_SYSTEM" in
-    *uclibc*)
-        ;;
-    *gnu*)
-        build_glibc
-        install_glibc;;
-    *)
-        echo "Unknown OS";;
-esac
+for action in $ACTIONS ; do
+    run_action $action
+done
 
-install_cross_toolchain_pkg
